variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build-GCC
  - build-Clang
  - test
  - coverage
  - quality
  - deploy

include:
#  - ".gitlab/ci/build-tests-freertos.yml"
#  - ".gitlab/ci/build-tests-standard.yml"
  - ".gitlab/ci/coverage-standard.yml"
#  - ".gitlab/ci/docs.yml"
  - ".gitlab/ci/quality.yml"
#  - ".gitlab/ci/run-tests-standard.yml"
